export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';

// authState
export const AUTH_REGISTRO_EXITOSO = 'AUTH_REGISTRO_EXITOSO';
export const AUTH_REGISTRO_ERROR = 'AUTH_REGISTRO_ERROR';
export const AUTH_LOGIN_EXITO = 'AUTH_LOGIN_EXITO';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_CERRAR_SESION = 'AUTH_CERRAR_SESION';
export const AUTH_AUTENTICADO_EXITO = 'AUTH_AUTENTICADO_EXITO';
export const AUTH_AUTENTICADO_ERROR = 'AUTH_AUTENTICADO_ERROR';
